In [29]:
import pandas as pd 
import numpy as np

In [374]:
import glob
import os
path = '../data/raw/box/'
csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]

In [375]:
csv_files

['545.csv',
 '223.csv',
 '237.csv',
 '551.csv',
 '579.csv',
 '586.csv',
 '592.csv',
 '021.csv',
 '035.csv',
 '009.csv',
 '155.csv',
 '141.csv',
 '169.csv',
 '196.csv',
 '182.csv',
 '431.csv',
 '357.csv',
 '343.csv',
 '425.csv',
 '419.csv',
 '394.csv',
 '380.csv',
 '381.csv',
 '395.csv',
 '418.csv',
 '342.csv',
 '424.csv',
 '430.csv',
 '356.csv',
 '183.csv',
 '197.csv',
 '168.csv',
 '140.csv',
 '154.csv',
 '008.csv',
 '034.csv',
 '020.csv',
 '593.csv',
 '587.csv',
 '578.csv',
 '236.csv',
 '550.csv',
 '544.csv',
 '222.csv',
 '552.csv',
 '234.csv',
 '220.csv',
 '546.csv',
 '208.csv',
 '591.csv',
 '585.csv',
 '036.csv',
 '022.csv',
 '142.csv',
 '624.csv',
 '156.csv',
 '618.csv',
 '181.csv',
 '195.csv',
 '426.csv',
 '340.csv',
 '354.csv',
 '432.csv',
 '368.csv',
 '383.csv',
 '397.csv',
 '396.csv',
 '382.csv',
 '369.csv',
 '355.csv',
 '433.csv',
 '427.csv',
 '341.csv',
 '194.csv',
 '180.csv',
 '619.csv',
 '157.csv',
 '143.csv',
 '625.csv',
 '023.csv',
 '037.csv',
 '584.csv',
 '590.csv',
 '209.csv',
 '221.csv',
 '547.csv',
 '553.csv',
 '235.csv',
 '219.csv',
 '231.csv',
 '557.csv',
 '543.csv',
 '225.csv',
 '594.csv',
 '580.csv',
 '033.csv',
 '027.csv',
 '609.csv',
 '621.csv',
 '147.csv',
 '153.csv',
 '184.csv',
 '190.csv',
 '379.csv',
 '345.csv',
 '423.csv',
 '437.csv',
 '351.csv',
 '386.csv',
 '392.csv',
 '393.csv',
 '387.csv',
 '436.csv',
 '350.csv',
 '344.csv',
 '422.csv',
 '378.csv',
 '191.csv',
 '185.csv',
 '152.csv',
 '620.csv',
 '146.csv',
 '608.csv',
 '026.csv',
 '032.csv',
 '581.csv',
 '595.csv',
 '542.csv',
 '224.csv',
 '230.csv',
 '556.csv',
 '218.csv',
 '568.csv',
 '226.csv',
 '540.csv',
 '554.csv',
 '232.csv',
 '583.csv',
 '597.csv',
 '018.csv',
 '024.csv',
 '030.csv',
 '178.csv',
 '150.csv',
 '144.csv',
 '622.csv',
 '193.csv',
 '187.csv',
 '408.csv',
 '352.csv',
 '434.csv',
 '420.csv',
 '346.csv',
 '391.csv',
 '385.csv',
 '384.csv',
 '390.csv',
 '421.csv',
 '347.csv',
 '353.csv',
 '435.csv',
 '409.csv',
 '186.csv',
 '192.csv',
 '145.csv',
 '623.csv',
 '151.csv',
 '179.csv',
 '031.csv',
 '025.csv',
 '019.csv',
 '596.csv',
 '582.csv',
 '555.csv',
 '233.csv',
 '227.csv',
 '541.csv',
 '569.csv',
 '240.csv',
 '526.csv',
 '532.csv',
 '254.csv',
 '268.csv',
 '283.csv',
 '297.csv',
 '042.csv',
 '056.csv',
 '081.csv',
 '095.csv',
 '136.csv',
 '122.csv',
 '334.csv',
 '452.csv',
 '446.csv',
 '320.csv',
 '308.csv',
 '491.csv',
 '485.csv',
 '484.csv',
 '490.csv',
 '309.csv',
 '447.csv',
 '321.csv',
 '335.csv',
 '453.csv',
 '123.csv',
 '137.csv',
 '094.csv',
 '080.csv',
 '057.csv',
 '043.csv',
 '296.csv',
 '282.csv',
 '269.csv',
 '533.csv',
 '255.csv',
 '241.csv',
 '527.csv',
 '257.csv',
 '531.csv',
 '525.csv',
 '243.csv',
 '519.csv',
 '294.csv',
 '280.csv',
 '055.csv',
 '041.csv',
 '069.csv',
 '096.csv',
 '082.csv',
 '121.csv',
 '135.csv',
 '109.csv',
 '323.csv',
 '445.csv',
 '451.csv',
 '337.csv',
 '479.csv',
 '486.csv',
 '492.csv',
 '493.csv',
 '487.csv',
 '478.csv',
 '450.csv',
 '336.csv',
 '322.csv',
 '444.csv',
 '108.csv',
 '134.csv',
 '120.csv',
 '083.csv',
 '097.csv',
 '068.csv',
 '040.csv',
 '054.csv',
 '281.csv',
 '295.csv',
 '518.csv',
 '524.csv',
 '242.csv',
 '256.csv',
 '530.csv',
 '508.csv',
 '534.csv',
 '252.csv',
 '246.csv',
 '520.csv',
 '291.csv',
 '285.csv',
 '078.csv',
 '050.csv',
 '044.csv',
 '093.csv',
 '087.csv',
 '118.csv',
 '124.csv',
 '130.csv',
 '468.csv',
 '440.csv',
 '326.csv',
 '332.csv',
 '454.csv',
 '483.csv',
 '497.csv',
 '496.csv',
 '482.csv',
 '333.csv',
 '455.csv',
 '441.csv',
 '327.csv',
 '469.csv',
 '131.csv',
 '125.csv',
 '119.csv',
 '086.csv',
 '092.csv',
 '045.csv',
 '051.csv',
 '079.csv',
 '284.csv',
 '290.csv',
 '247.csv',
 '521.csv',
 '535.csv',
 '253.csv',
 '509.csv',
 '279.csv',
 '523.csv',
 '245.csv',
 '251.csv',
 '537.csv',
 '286.csv',
 '292.csv',
 '047.csv',
 '053.csv',
 '084.csv',
 '090.csv',
 '133.csv',
 '127.csv',
 '319.csv',
 '457.csv',
 '331.csv',
 '325.csv',
 '443.csv',
 '494.csv',
 '480.csv',
 '481.csv',
 '495.csv',
 '324.csv',
 '442.csv',
 '456.csv',
 '330.csv',
 '318.csv',
 '126.csv',
 '132.csv',
 '091.csv',
 '085.csv',
 '052.csv',
 '046.csv',
 '293.csv',
 '287.csv',
 '250.csv',
 '536.csv',
 '522.csv',
 '244.csv',
 '278.csv',
 '261.csv',
 '507.csv',
 '513.csv',
 '275.csv',
 '249.csv',
 '063.csv',
 '077.csv',
 '088.csv',
 '117.csv',
 '103.csv',
 '315.csv',
 '473.csv',
 '467.csv',
 '301.csv',
 '329.csv',
 '498.csv',
 '499.csv',
 '328.csv',
 '466.csv',
 '300.csv',
 '314.csv',
 '472.csv',
 '102.csv',
 '116.csv',
 '089.csv',
 '076.csv',
 '062.csv',
 '248.csv',
 '512.csv',
 '274.csv',
 '260.csv',
 '506.csv',
 '276.csv',
 '510.csv',
 '504.csv',
 '262.csv',
 '538.csv',
 '289.csv',
 '074.csv',
 '060.csv',
 '048.csv',
 '100.csv',
 '114.csv',
 '128.csv',
 '302.csv',
 '464.csv',
 '470.csv',
 '316.csv',
 '458.csv',
 '459.csv',
 '471.csv',
 '317.csv',
 '303.csv',
 '465.csv',
 '129.csv',
 '115.csv',
 '101.csv',
 '049.csv',
 '061.csv',
 '075.csv',
 '288.csv',
 '539.csv',
 '505.csv',
 '263.csv',
 '277.csv',
 '511.csv',
 '529.csv',
 '515.csv',
 '273.csv',
 '267.csv',
 '501.csv',
 '298.csv',
 '059.csv',
 '071.csv',
 '065.csv',
 '139.csv',
 '105.csv',
 '111.csv',
 '449.csv',
 '461.csv',
 '307.csv',
 '313.csv',
 '475.csv',
 '312.csv',
 '474.csv',
 '460.csv',
 '306.csv',
 '448.csv',
 '110.csv',
 '104.csv',
 '138.csv',
 '064.csv',
 '070.csv',
 '058.csv',
 '299.csv',
 '266.csv',
 '500.csv',
 '514.csv',
 '272.csv',
 '528.csv',
 '258.csv',
 '502.csv',
 '264.csv',
 '270.csv',
 '516.csv',
 '066.csv',
 '072.csv',
 '099.csv',
 '112.csv',
 '106.csv',
 '338.csv',
 '476.csv',
 '310.csv',
 '304.csv',
 '462.csv',
 '489.csv',
 '488.csv',
 '305.csv',
 '463.csv',
 '477.csv',
 '311.csv',
 '339.csv',
 '107.csv',
 '113.csv',
 '098.csv',
 '073.csv',
 '067.csv',
 '271.csv',
 '517.csv',
 '503.csv',
 '265.csv',
 '259.csv',
 '564.csv',
 '202.csv',
 '216.csv',
 '570.csv',
 '558.csv',
 '000.csv',
 '014.csv',
 '028.csv',
 '174.csv',
 '612.csv',
 '606.csv',
 '160.csv',
 '148.csv',
 '410.csv',
 '376.csv',
 '362.csv',
 '404.csv',
 '438.csv',
 '389.csv',
 '388.csv',
 '439.csv',
 '363.csv',
 '405.csv',
 '411.csv',
 '377.csv',
 '149.csv',
 '607.csv',
 '161.csv',
 '175.csv',
 '613.csv',
 '029.csv',
 '015.csv',
 '001.csv',
 '559.csv',
 '217.csv',
 '571.csv',
 '565.csv',
 '203.csv',
 '573.csv',
 '215.csv',
 '201.csv',
 '567.csv',
 '229.csv',
 '598.csv',
 '017.csv',
 '003.csv',
 '163.csv',
 '605.csv',
 '611.csv',
 '177.csv',
 '188.csv',
 '407.csv',
 '361.csv',
 '375.csv',
 '413.csv',
 '349.csv',
 '348.csv',
 '374.csv',
 '412.csv',
 '406.csv',
 '360.csv',
 '189.csv',
 '610.csv',
 '176.csv',
 '162.csv',
 '604.csv',
 '002.csv',
 '016.csv',
 '599.csv',
 '228.csv',
 '200.csv',
 '566.csv',
 '572.csv',
 '214.csv',
 '238.csv',
 '210.csv',
 '576.csv',
 '562.csv',
 '204.csv',
 '589.csv',
 '012.csv',
 '006.csv',
 '600.csv',
 '166.csv',
 '172.csv',
 '614.csv',
 '199.csv',
 '358.csv',
 '364.csv',
 '402.csv',
 '416.csv',
 '370.csv',
 '417.csv',
 '371.csv',
 '365.csv',
 '403.csv',
 '359.csv',
 '198.csv',
 '173.csv',
 '615.csv',
 '601.csv',
 '167.csv',
 '007.csv',
 '013.csv',
 '588.csv',
 '563.csv',
 '205.csv',
 '211.csv',
 '577.csv',
 '239.csv',
 '549.csv',
 '207.csv',
 '561.csv',
 '575.csv',
 '213.csv',
 '039.csv',
 '005.csv',
 '011.csv',
 '159.csv',
 '617.csv',
 '171.csv',
 '165.csv',
 '603.csv',
 '429.csv',
 '373.csv',
 '415.csv',
 '401.csv',
 '367.csv',
 '398.csv',
 '399.csv',
 '400.csv',
 '366.csv',
 '372.csv',
 '414.csv',
 '428.csv',
 '164.csv',
 '602.csv',
 '616.csv',
 '170.csv',
 '158.csv',
 '010.csv',
 '004.csv',
 '038.csv',
 '574.csv',
 '212.csv',
 '206.csv',
 '560.csv',
 '548.csv']

In [381]:
#clean up data, remove spaces
#concatenate values for column 8 (text field)
def get_clean_df(filename):
    filepath = '../data/raw/box/'+filename
    to_write_filepath = '../data/interim/'+filename
    df = pd.read_csv(filepath, header=None, sep='\n')
    df = df[0].str.split(',', expand=True)
    temp = df.copy() 
    temp[temp.columns] = temp.apply(lambda x: x.str.strip())
    temp.fillna('', inplace=True)
    temp[8]= temp[8].str.cat(temp.iloc[:,9:-1], sep =", ") 
    temp[temp.columns] = temp.apply(lambda x: x.str.rstrip(", ,"))
    temp = temp.loc[:, :8]
    
    temp.to_csv(to_write_filepath, index=False)
    
    return temp

In [382]:
for files in csv_files:
    get_clean_df(files)

In [365]:
df2 = get_clean_df('001')

In [359]:
#read key value dict 
df = pd.read_json('../data/raw/key/012.json',typ='series')

In [360]:
df.to_frame().reset_index()

     index                                                  0
0  company                  HOME MASTER HARDWARE & ELECTRICAL
1     date                                         22/12/2017
2  address  NO.113G & 115G, JALAN SETIA GEMBILANG U13/BG B...
3    total                                              15.90

In [272]:
address = "NO.53 55,57 & 59, JALAN SAGU 18, TAMAN DAYA, 81100 JOHOR BAHRU, JOHOR."

In [273]:
my_list = address.split(',')

In [274]:
my_list = [x.strip(' ') for x in my_list]

In [275]:
my_list

['NO.53 55',
 '57 & 59',
 'JALAN SAGU 18',
 'TAMAN DAYA',
 '81100 JOHOR BAHRU',
 'JOHOR.']

In [276]:
'|'.join(my_list)

'NO.53 55|57 & 59|JALAN SAGU 18|TAMAN DAYA|81100 JOHOR BAHRU|JOHOR.'

In [277]:
df2[df2[8].str.contains('|'.join(my_list))]

     0    1    2    3    4    5    6    7                                 8
1   50   82  440   82  440  121   50  121    BOOK TA .K(TAMAN DAYA) SDN BND
3  110  144  383  144  383  163  110  163  NO.53 55, 57 & 59, JALAN SAGU 18
4  192  169  299  169  299  187  192  187                        TAMAN DAYA
5  162  193  334  193  334  211  162  211                 81100 JOHOR BAHRU
6  217  216  275  216  275  233  217  233                            JOHOR.

In [285]:
my_list2 = "BOOK TA .K (TAMAN DAYA) SDN BHD"

In [279]:
my_list2 = my_list2.split(',')

In [280]:
my_list2 = [x.strip(' ') for x in my_list2]

In [281]:
'|'.join(my_list2)

'BOOK TA .K (TAMAN DAYA) SDN BHD'

In [282]:
my_list2

['BOOK TA .K (TAMAN DAYA) SDN BHD']

In [318]:
asd = '|'.join(my_list2)

In [326]:
Str1 = "NO.53 55,57 & 59, JALAN SAGU 18, TAMAN DAYA, 81100 JOHOR BAHRU, JOHOR."
Str2 = "NO.53 55,57 & 59"
Str2 in (Str1)

True

In [333]:
df2[8] in asd

TypeError: 'in <string>' requires string as left operand, not numpy.ndarray

In [306]:
import numpy as np
#Using The Levenshtein Distance
def levenshtein_ratio_and_distance(s, t, ratio_calc = False):
    """ levenshtein_ratio_and_distance:
        Calculates levenshtein distance between two strings.
        If ratio_calc = True, the function computes the
        levenshtein distance ratio of similarity between two strings
        For all i and j, distance[i,j] will contain the Levenshtein
        distance between the first i characters of s and the
        first j characters of t
    """
    # Initialize matrix of zeros
    rows = len(s)+1
    cols = len(t)+1
    distance = np.zeros((rows,cols),dtype = int)

    # Populate matrix of zeros with the indeces of each character of both strings
    for i in range(1, rows):
        for k in range(1,cols):
            distance[i][0] = i
            distance[0][k] = k

    # Iterate over the matrix to compute the cost of deletions,insertions and/or substitutions    
    for col in range(1, cols):
        for row in range(1, rows):
            if s[row-1] == t[col-1]:
                cost = 0 # If the characters are the same in the two strings in a given position [i,j] then the cost is 0
            else:
                # In order to align the results with those of the Python Levenshtein package, if we choose to calculate the ratio
                # the cost of a substitution is 2. If we calculate just distance, then the cost of a substitution is 1.
                if ratio_calc == True:
                    cost = 2
                else:
                    cost = 1
            distance[row][col] = min(distance[row-1][col] + 1,      # Cost of deletions
                                 distance[row][col-1] + 1,          # Cost of insertions
                                 distance[row-1][col-1] + cost)     # Cost of substitutions
    if ratio_calc == True:
        # Computation of the Levenshtein Distance Ratio
        Ratio = ((len(s)+len(t)) - distance[row][col]) / (len(s)+len(t))
        return Ratio
    else:
        # print(distance) # Uncomment if you want to see the matrix showing how the algorithm computes the cost of deletions,
        # insertions and/or substitutions
        # This is the minimum number of edits needed to convert string a to string b
        return "The strings are {} edits away".format(distance[row][col])

In [336]:
Str1 = "BOOK TA .K (TAMAN DAYA) SDN BND"
Str2 = "BOOK TA .K(TAMAN DAYA) SDN BND"
Distance = levenshtein_ratio_and_distance(Str1,Str2)
print(Distance)
Ratio = levenshtein_ratio_and_distance(Str1,Str2,ratio_calc = True)
print(Ratio)

The strings are 1 edits away
0.9836065573770492

In [337]:
Str1 = "NO.53 55,57 & 59, JALAN SAGU 18, TAMAN DAYA, 81100 JOHOR BAHRU, JOHOR."
Str2 = "NO.53 55,57 & 59"
Distance = levenshtein_ratio_and_distance(Str1,Str2)
print(Distance)
Ratio = levenshtein_ratio_and_distance(Str1,Str2,ratio_calc = True)
print(Ratio)

The strings are 54 edits away
0.37209302325581395

In [338]:
import re 
  
# Take input from users 
MyString1 = "NO.53 55,57 & 59, JALAN SAGU 18, TAMAN DAYA, 81100 JOHOR BAHRU, JOHOR."
MyString2 = "NO.53 55,57 & 59"
MyString2 = "RM"
  
# re.search() returns a Match object if there is a match anywhere in the string 
if re.search( MyString2, MyString1): 
    print("YES,string '{0}' is present in string '{1}' " .format(MyString2,MyString1)) 
else: 
    print("NO,string '{0}' is not present in string {1} " .format(MyString2, MyString1) )

NO,string 'RM' is not present in string NO.53 55,57 & 59, JALAN SAGU 18, TAMAN DAYA, 81100 JOHOR BAHRU, JOHOR.

# get the last 'total' value from df

In [347]:
date_pattern = '^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(19|20)\d\d$'

In [356]:
if re.match(date_pattern,"18/01/2018"):
    print('yes')
else:
    print('no')

yes